apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: portfolio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-role
  namespace: portfolio
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["build.openshift.io"]
    resources: ["buildconfigs", "buildconfigs/instantiate", "builds", "builds/log"]
    verbs: ["get", "list", "create", "watch"]
  - apiGroups: ["image.openshift.io"]
    resources: ["imagestreams", "imagestreamtags"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-rolebinding
  namespace: portfolio
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: portfolio
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: pipeline-role
