  replicaCount: 2
  image:
    repository: image-registry.openshift-image-registry.svc:5000/portfolio/portfolio
    tag: latest
    pullPolicy: Always
  service:
    port: 3000
    targetPort: 3000
  route:
    enabled: true
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
